const double KDOUBLE5 = 5.0;
const double KDOUBLE8 = 8.0;
const double KDOUBLE10 = 10.0;
const double KDOUBLE20 = 20.0;
const double KDOUBLE22 = 22.0;
const double KDOUBLE40 = 40.0;
const double KDOUBLE100 = 100.0;

const String BACON_IPSUM_CONSTANT =
    """Bacon ipsum dolor amet beef meatball turkey pork chop landjaeger leberkas rump frankfurter swine chuck porchetta prosciutto bacon. Salami biltong corned beef cow pork doner shoulder ball tip pork chop shankle cupim. Cupim short loin turkey tenderloin drumstick ham hock shoulder leberkas salami shankle ground round cow. Pig pork belly pork loin tail beef ribs. Kevin boudin hamburger pancetta chuck brisket pig chicken frankfurter jowl sirloin sausage. Buffalo turkey tail jowl pig kevin ball tip chuck cow capicola.Tri-tip pastrami bresaola short loin jerky chicken. Frankfurter chuck boudin, capicola andouille bacon shankle filet mignon cupim ham hock ham drumstick short ribs ball tip rump. Ball tip porchetta short ribs tri-tip, ham hock buffalo brisket spare ribs rump burgdoggen. Tongue strip steak chicken doner sirloin corned beef biltong pig swine tail shankle brisket ball tip meatball. Fatback short ribs cupim pork doner beef porchetta jerky drumstick capicola andouille chicken. Beef ribs shoulder ham, turducken spare ribs hamburger beef short loin meatball venison chuck tail cow.
Beef kielbasa jerky short loin ham sausage capicola cow chuck tenderloin short ribs boudin frankfurter turducken picanha. Alcatra ham hock meatloaf bacon turkey landjaeger cow pork loin swine. Tail ham turducken chicken shank, biltong burgdoggen cow jowl pork chop. Landjaeger pancetta frankfurter t-bone hamburger boudin turkey chicken strip steak rump short loin jowl filet mignon meatball. Pastrami flank burgdoggen strip steak shoulder leberkas ball tip filet mignon swine, venison jerky landjaeger biltong. Jerky chicken short ribs kevin. Brisket buffalo shank filet mignon, tenderloin meatloaf frankfurter flank.
Doner prosciutto burgdoggen flank sirloin buffalo short loin, cupim venison jerky andouille meatloaf ham. Spare ribs brisket swine shankle, boudin beef sausage leberkas ground round pork chop pig bacon. Pork chop short loin ham rump kevin cupim meatball ground round swine bresaola chislic t-bone pig buffalo. Pork chop t-bone kevin ham hock short ribs. Chislic picanha pastrami tongue buffalo ham hock. Corned beef brisket hamburger biltong. Venison pork chop ball tip flank bresaola tongue short loin rump.
Pork chop bresaola sirloin, drumstick salami filet mignon hamburger spare ribs swine beef ribs buffalo biltong pancetta. Leberkas pork belly brisket bacon boudin flank jerky meatball ground round alcatra cow venison turducken ham void tongue. T-bone pork belly kevin rump, meatloaf tongue strip steak turkey. Turkey turducken alcatra tail. Ball tip cow ham hock porchetta chicken tri-tip hamburger jerky burgdoggen swine alcatra boudin. Ham jerky chuck, shoulder shankle boudin biltong doner salami strip void steak.""";
